Module7 task1
htmlacademy-ecmascript/393173-big-trip-15 pull request #12
Opened 2021-08-30 11:55 UTC by whataboutjuuu

2021-08-30 13:20 UTC, ekazakov commented on src/view/filters.js
> +    <form class="trip-filters" action="#" method="get">
Возможно проблема в переносе строки перед открывающим тэгом.
Попробуй сделать:
```
  `<form class="trip-filters" action="#" method="get"> ...
```

2021-09-01 14:41 UTC, ekazakov requested changes
В форме создания токчи кнопку Delete надо переименовать в Cancel. И еще не работает кнопка сворачивания.

2021-09-01 14:41 UTC, ekazakov commented on src/view/point-popup.js
> +    const reg = /^\d+$/;
Можно просто сделать `type="number"` для поля ввода и регулярка будет не нужна

2021-09-01 16:46 UTC, whataboutjuuu commented on src/view/point-popup.js
> +    const reg = /^\d+$/;
я подумала, что если просто поменять тип инпута, то злоумышленник может точно так же легко поменять его назад в текст в девтуле

2021-09-02 07:15 UTC, merged