Module8 task1
htmlacademy-ecmascript/393173-big-trip-15 pull request #14
Opened 2021-09-06 15:42 UTC by whataboutjuuu

2021-09-06 20:28 UTC, ekazakov requested changes
Еще по поводу маршрута в заголовке приложения

```
if (uniqueCities.length > 3) {
    route =
    `
    <h1 class="trip-info__title">${uniqueCities[0]} &mdash; ... &mdash; ${uniqueCities[uniqueCities.length - 1]}</h1>
    `;
  } else{
    route =
    `
    <h1 class="trip-info__title">${uniqueCities[0]} &mdash; ${uniqueCities[1]} &mdash; ${uniqueCities[2]}</h1>
    `;
  }
```

Проверка с кол-вом `uniqueCities` — правильная, но значения городов нада брать из первой и последней точки маршрута.

Если городов меньше четырех, то в идеале на заморочиться со случаями, когда у нас 0 точек, 1/2/3 уникальных города. Но это можно на потом оставить :)

2021-09-06 20:28 UTC, ekazakov commented on src/presenter/point-new.js
>      this._pointPopupComponent = new PointPopup();
В `new PointPopup()` потерялись аргументы(point, offersModel, destinationsModel)

2021-09-06 20:28 UTC, ekazakov commented on src/main.js
> +  pointsModel.setPoints(UpdateType.INIT, []);
В случае, если не удалось загрузить все данные, то лучше показать какое-нибудь сообщение об ошибке.

2021-09-07 20:47 UTC, ekazakov reviewed
Еще пару багов нашел:
1. Фильтры отвалились
2. Точки с сервера приходят не отсортированные, надо сортировать по дате начала

2021-09-07 20:47 UTC, ekazakov commented on src/api.js
> +    })
![image](https://user-images.githubusercontent.com/2683752/132407155-92d1acaa-fe55-4359-8ca6-bab3da315a4f.png)


Проблема с созданием точки, отправляется поле `photos`, а по ТЗ нужно `pictures`. Если ф

2021-09-08 18:03 UTC, whataboutjuuu commented on src/main.js
> +  pointsModel.setPoints(UpdateType.INIT, []);
Ошибка при загрузке обрабатывается в api.js Или ты о какой-то другой ошибке?

2021-09-09 14:06 UTC, ekazakov commented on src/main.js
> +  pointsModel.setPoints(UpdateType.INIT, []);
Я имею ввиду сообщение в интерфейсе

2021-09-09 14:26 UTC, merged